[Server]
verbose = false
timeout = 1

[Notifications]
discord_webhook = "BUTT_DISCORD"

# [[Websites]]
# name = "Google"
# url = "https://google.com"
# interval = 3.0

# [[Websites]]
# name = "Youtube"
# url = "https://youtube.com"
# interval = 8.0

[[Websites]]
name = "Fake Webiste"
url = "http://fuaeghfhkjadfv_sdjnvbwsdhkfukwehfbwehk.com"
# retry = 1
interval = 3.0
